### PR TITLE
feat: add basic templ support

### PR DESCRIPTION
**Pull request by tommsawyer**
Added basic support for templ files. Docs for templ commenting here: https://templ.guide/syntax-and-usage/comments

In general we are using html-style comments inside components, and go-style comments outside.

### CODE REVIEW

**Comment by haydenrou** [comment]
Something like this would be awesome out of the box, thanks! 

I've added the solution to [my own dotfiles here](https://github.com/haydenrou/dotfiles/pull/29/files) for the time-being. It works great except for one thing - the templ builtin function `templ myComponent() {` will be commented like `<!-- templ myComponent() { -->`. Is that something we could accommodate for?

**Comment by JoosepAlviste** [comment]
Hey, thanks for the PR! Supporting templ makes a lot of sense since it seems to be very similar to JSX.

In order to handle the `templ myComponent() {` line correctly, I think that we can use `component_block` instead of `component_declaration` as the node.

By the way, what should happen in the following lines?

```templ
package main

templ hello(name string) {
	<div>
        <h1>Howdy foks</h1>
        Hello, { name }

        <hr style="padding: 10px"
            if true {  <-- this line, for example, and the next one
                class="itIsTrue"
            }
        />
    </div>
}

```

Here's how it would work with `component_block`:

https://github.com/JoosepAlviste/nvim-ts-context-commentstring/assets/9450943/516e05d6-ef4f-4f50-96e2-a4eef6ec7124

**Comment by zyriab** [comment]
Hello! Any plan to merge this PR soon? :)

**Comment by JoosepAlviste** [comment]
Merged and pushed the small fix myself, thanks for the reminder 👍

**Pull request merged**
